#! /u/home/y/ybwang/perl

# get floss value for each region, against with coding region of known gene

use strict;
use warnings;
use File::Basename;
use Data::Table;
use 5.010;

#translateJuncStar($ARGV[0]);
#removeIdenJunc($ARGV[0]);
callCometSearch($ARGV[0],$ARGV[1]);
#callPercolator($ARGV[0]);

sub translateJuncStar {
	my $in = shift;

        my %hash = ();
        my $n = 1;
        while(<DATA>){
                chomp;
                $hash{$n} = $_;
                $n++;
        }

        die $in,"\n" if !exists $hash{$in};
	say "python ./translateJunc-star.py -o $hash{$in}.fa -l 66 --min-junc-reads=6 RNA/$hash{$in}/";
	system("python ./translateJunc-star.py -o $hash{$in}.fa -l 66 --min-junc-reads=6 RNA/$hash{$in}/");
}

sub removeIdenJunc {
	my $in = shift;

	my @list = `ls junctionPep/*.fa`;
	my %hash = ();
	my $n = 1;
	foreach(@list){
		chomp;
		s/.*\///g;
		$hash{$n} = $_;
		$n++;
	}

	die $in,"\n" if !exists $hash{$in};

	say "./removeIdenJunc.pl junctionPep/$hash{$in}";
	system("./removeIdenJunc.pl junctionPep/$hash{$in}");
}


sub callCometSearch {
	my $rawindex = shift or die "$0 raw db";
	my $indb = shift or die "$0 raw db"; # GM19127.rna
	
	mkdir 'cometout' if !-e 'cometout';
	my $db = "/u/home/y/ybwang/scratch/HumanSpecificExon/massDb/merge_".basename($indb).".fa";
	my $outdir = "/u/home/y/ybwang/scratch/HumanSpecificExon/cometout/".basename($indb);
	mkdir $outdir if !-e $outdir;
	#my $rawdir = "/u/home/y/ybwang/scratch/Yoav_Gilad_proteom/".basename($indb);
	my $rawdir = "/u/home/y/ybwang/scratch/Mathias_Wilhelm/proteom";
	$rawdir =~ s/\..*$//g;
	my @rawfiles = `ls $rawdir/*.raw`;

	my %hash = ();
	my $n = 1;
	foreach(@rawfiles){
	        chomp;
        	$hash{$n} = $_;
	        $n++;
	}

	say "/u/home/y/ybwang/comet/bin/search.pl -e /u/home/y/ybwang/comet/bin/comet.2015025.win64.exe -p /u/home/y/ybwang/comet/comet_22.params -d $db -o $outdir -f $hash{$rawindex}";
	system("/u/home/y/ybwang/comet/bin/search.pl -e /u/home/y/ybwang/comet/bin/comet.2015025.win64.exe -p /u/home/y/ybwang/comet/comet_22.params -d $db -o $outdir -f $hash{$rawindex}");
}

sub callPercolator {
        my $in = shift or die "$0 raw db"; # GM19127.rna

        my @rawfiles = `ls cometout/`;

        my %hash = ();
        my $n = 1;
        foreach(@rawfiles){
                chomp;
                $hash{$n} = $_;
                $n++;
        }

        say "/u/home/y/ybwang/comet/callPercolator.pl -f 'cometout/$hash{$in}/*.pin'";
        system("/u/home/y/ybwang/comet/callPercolator.pl -f 'cometout/$hash{$in}/*.pin'");
}

__DATA__
GM18486.rna
GM18498.rna
GM18499.rna
GM18501.rna
GM18502.rna
GM18504.rna
GM18505.rna
GM18507.rna
GM18508.rna
GM18510.rna
GM18511.rna
GM18516.rna
GM18517.rna
GM18519.rna
GM18520.rna
GM18522.rna
GM18523.rna
GM18852.rna
GM18853.rna
GM18855.rna
GM18856.rna
GM18858.rna
GM18861.rna
GM18862.rna
GM18870.rna
GM18909.rna
GM18912.rna
GM18913.rna
GM18916.rna
GM19093.rna
GM19098.rna
GM19099.rna
GM19101.rna
GM19102.rna
GM19108.rna
GM19114.rna
GM19116.rna
GM19119.rna
GM19127.rna
GM19128.rna
GM19130.rna
GM19131.rna
GM19137.rna
GM19138.rna
GM19140.rna
GM19141.rna
GM19143.rna
GM19144.rna
GM19147.rna
GM19152.rna
GM19153.rna
GM19159.rna
GM19160.rna
GM19171.rna
GM19172.rna
GM19190.rna
GM19192.rna
GM19193.rna
GM19200.rna
GM19201.rna
GM19204.rna
GM19207.rna
GM19209.rna
GM19210.rna
GM19222.rna
GM19225.rna
GM19238.rna
GM19239.rna
GM19257.rna

